#!/usr/bin/sh

# Installs our dependencies in a virtual environment.
sudo apt update && sudo apt install -y python3-virtualenv
virtualenv .venv
. .venv/bin/activate
pip install -r object_tracker_0/requirements.txt
pip install -e external/segment-anything-2/

# Log-in to Google Cloud using user's credentials
# TODO(adamantivm) Replace with file-based credential access
gcloud auth application-default login
