#!/bin/bash
# Silly script that queries MLFlow projects, to keep it busy and avoid Ploomber from shutting it down
curl -X GET \
  https://soft-pond-5082.ploomberapp.io/api/2.0/mlflow/experiments/search \
  -d '{"max_results": "100"}' \
  -H 'Authorization: Basic YWRtaW46VzNBcmVMYXp5IQ==' \
  -H 'Content-Type: application/json'
